### ISSUE TITLE
No path specified Error while using gulp cache with WebFundamentalsKit

### ISSUE THREAD

**Issue by rayabhagis** [jgable/gulp-cache#30]
Gulp v: 3.8.7 and gulp-cache (map-stream): 0.1.0

Here is the task in gulpjs file

``` js
// Optimize Images
gulp.task('images', function () {
  return gulp.src('app/images/**/*')
    .pipe($.cache($.imagemin({
      progressive: true,
      interlaced: true
    })))
    .pipe(gulp.dest('dist/images'))
    .pipe($.size({title: 'images'}));
});
```

and when I try using `gulp images` and this is the error I see.

```
[01:00:05] Starting 'images'...
Possibly unhandled Error: No path specified! Can not get relative.
    at File.Object.defineProperty.get (/Users/rayabhagis/projects/nerdtogeeks.com/node_modules/gulp/node_modules/vinyl-fs/node_modules/vinyl/index.js:150:27)
    at DestroyableTransform.saveFile [as _transform] (/Users/rayabhagis/projects/nerdtogeeks.com/node_modules/gulp/node_modules/vinyl-fs/lib/dest/index.js:40:48)
    at DestroyableTransform.Transform._read (/Users/rayabhagis/projects/nerdtogeeks.com/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/rayabhagis/projects/nerdtogeeks.com/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/rayabhagis/projects/nerdtogeeks.com/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/rayabhagis/projects/nerdtogeeks.com/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/rayabhagis/projects/nerdtogeeks.com/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.EventEmitter.emit (events.js:95:17)
    at queueData (/Users/rayabhagis/projects/nerdtogeeks.com/node_modules/gulp-cache/node_modules/map-stream/index.js:43:21)
```

But I can evade this one by just removing 

``` js
.pipe($.cache($.imagemin({
      progressive: true,
      interlaced: true
    })))
```

part from the gulp task

**Comment by sabarigr** [comment]
Hi. Sorry to bother. But I am facing this `The system cannot find the path specified` error while running the images gulp task.

Here is my code
```
gulp.task('images', function () {
       $.cache.clearAll();
	return gulp.src('app/images/**/*')
		.pipe($.cache($.imagemin({
			progressive: true,
			interlaced: true,
			optimizationLevel: 5
		})))
		.pipe(gulp.dest('dist/images'))
		.pipe($.size({
			title: 'images'
		}));
});
```

I tried clearing the cache as suggested above but with no end result. Please help.

**Comment by jgable** [comment]
Do you have `app/images/**/*` and `dist/images` folders?  Is there a stack
trace pointing into the gulp-cache code?
