### ISSUE TITLE
Broken with latest @babel/runtime v7.3.0

### ISSUE THREAD

**Issue by huochunpeng** [jgable/gulp-cache#75]
With latest `@babel/runtime` v7.3.0,

 TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyDescriptors (<anonymous>)
    at _objectSpread (/Users/huocp/bw/bcx-broker-au-frontend/node_modules/@babel/runtime/helpers/objectSpread.js:19:46)
    at plugin (/Users/huocp/bw/bcx-broker-au-frontend/node_modules/gulp-cache/lib/index.js:491:19)
    at buildJs (/Users/huocp/bw/bcx-broker-au-frontend/gulpfile.js:102:17)
    at build (/Users/huocp/bw/bcx-broker-au-frontend/gulpfile.js:128:5)

Caused by this:
https://github.com/jgable/gulp-cache/blob/37039dc9f4eadae30ba840426ef411645a05921d/src/index.js#L75-L78

The `task.cacheable` is undefined, causing `@babel/runtime` to fail.

This seems caused by the compiled code `lib/index.js` is based on old babel version (presets, plugins?).

Two possible fixes:
1. (tested) fix the dep of `@babel/runtime` in package.json to `"@babel/runtime": "~7.2.0"`, pinning it to 7.2.x.
2. (not tested yet) update all deps, and publish recompiled file.

**Comment by huochunpeng** [comment]
There is another possible fix. Remove `@babel/runtime`, don't use `transform-runtime` (provided by babel-preset-trigen).

That will result in slightly bigger code, but immune to future babel changes.

**Comment by dangreen** [comment]
@huochunpeng Please try https://github.com/jgable/gulp-cache/releases/tag/v1.1.1

**Comment by huochunpeng** [comment]
It works!
