### ISSUE TITLE
\node_modules\gulp-cache\lib\index.js:60 SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by jbracoupeau** [jgable/gulp-cache#81]
Hey guys I'm running the same project on my mac and my PC. My colleague added gulp-cache to it recently (on his mac), and since then I can't work from my PC anymore because of an issue with gulp-cache, it works just fine on my mac as well as on my colleague's mac.

Here's the version we're using : "gulp-cache": "^1.1.3"

I've tried removing it and reinstalling it, and also removing my node_modules dir and reinstalling everything, same issue.

$ gulp --env=dev

C:\wamp\www\GamingSchool\symfony\node_modules\gulp-cache\lib\index.js:60
  async _processFileAsync(inputFile, signals = new EventEmitter()) {
        ^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\wamp\www\GamingSchool\symfony\gulpfile.js:18:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by dangreen** [comment]
@jbracoupeau Which nodejs version you have?

**Comment by jbracoupeau** [comment]
omg I didn't even think about that, I've updated npm on my PC and have a 100 other problems now, but hopefully once they're solved I'll get everything to work, sorry !
